[package]
name = "chip8emu"
version = "0.1.0"
authors = ["Abhishek Kadam <lycuid@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "*"
wasm-bindgen = "*"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
